### ISSUE TITLE
User ID is not set when creating sessions

### ISSUE THREAD

**Issue by tnoczyns-volue** [Volue-Public/energy-mesh-python#337]
When creating new session the user ID is not set on the server side. That results in "unknown user" entries in Event Log even if authorization is enabled.

The fix is needed on server-side only. No changes in Python SDK are needed.

**Comment by alftester** [comment]
Have you planned when you are to look at this?

**Comment by tnoczyns-volue** [comment]
We will have planning session on January 9th, then I'll come back with more information.

**Comment by tnoczyns-volue** [comment]
@alftester: the plan is to implement this in Mesh 2.7, that is going to be released beginning of February.

**Comment by tnoczyns-volue** [comment]
Feature implemented, the user display name should be visible in the Event Log with Mesh 2.7.

![image](https://user-images.githubusercontent.com/88330807/213142015-f5be2d91-3492-42a9-a395-bbb140326596.png)
