### ISSUE TITLE
Adjust to removal of `return_no_attributes` from `AttributesMasks` message

### ISSUE THREAD

**Issue by tnoczyns-volue** [Volue-Public/energy-mesh-python#423]
Adjust to proto changes that will be done in https://github.com/Volue/energy-mesh/issues/5013.

From Python SDK side we need to adjust `return_no_attributes` from the `AttributesFilter` class. So that if the `return_no_attributes` is set then `attributes` field mask is not set. Best be done together with #385.

PS: Add a test to when `return_no_attributes` is set to True, but at the same time we set also `full_attribute_info` to True.

The changes won't break the Python SDK API.

**Comment by simia** [comment]
Resolved by #436
