### ISSUE TITLE
Prepare 1.7 release

### ISSUE THREAD

**Issue by tnoczyns-volue** [Volue-Public/energy-mesh-python#448]
- [x] Use latest 2.13 official build, i.e.: 2.13.1.14
- [x] Update versions.rst
- [x] Update the Python SDK version to official one (without `-dev` suffix)
- [x] Release 1.7 version, take previous release description template as base
- [x] Check locally the installation steps from https://volue-public.github.io/energy-mesh-python/versions.html#install-instructions.
- [x] Bump version and add `-dev` suffix

**Comment by tnoczyns-volue** [comment]
Done.

**Comment by erny-powel** [comment]
Woho!
