### ISSUE TITLE
Examples and tests are not exposed

### ISSUE THREAD

**Issue by jbbakeng** [Volue-Public/energy-mesh-python#455]
Examples:
According to the documentation: 
- ["These examples are packaged with the Mesh Python SDK and can be accessed when the package is installed"](https://volue-public.github.io/energy-mesh-python/examples.html)

Tests:
According to the documentation:
- ["The Mesh Python SDK is shipped with tests that are used to verify its functionality. (...) To be able to run the tests there you need pytest and pytest-asyncio. (...)"](https://volue-public.github.io/energy-mesh-python/tests.html)

They are indeed inside the package, but they are no longer exposed. From the documentation I would expect to be able to write:

```python
from volue.mesh.examples import get_version

get_version.main("localhost", 50051, "")
```
I would like for the examples and test to be exposed in the package as a quality of life feature and for the documentation to explicitly show how to use it.

**Comment by tnoczyns-volue** [comment]
We had a nice discussion with @jbbakeng and for now we've decided to:
* Update the documentation about examples (best practices, copy the examples code from repo, etc.).
* Remove tests section from documentation.
* Continue to not expose the examples, at least for now.
