### ISSUE TITLE
Installing PythonSDK from zip package: missing dependencies

### ISSUE THREAD

**Issue by AKRittinghausen** [Volue-Public/energy-mesh-python#512]
Mesh Python SDK version: volue.mesh-1.9.0
Mesh version: 2.15
Python version: 3.11.8
Operating System (Windows, Ubuntu, etc.): Windows 64

Hey there! 

I would like to **install the Python SDK package from a zip file without using the internet**

+ First I downloaded the zip folder using `python -m pip download git+https://github.com/Volue-Public/energy-mesh-python@v1.9.0`
+ Then, I made sure I installed all dependencies listed in the pyproject.toml file, my environment looks like this: 

`Package                       Version
----------------------------- -----------
alabaster                     1.0.0
babel                         2.16.0
bidict                        0.23.1
certifi                       2024.8.30
charset-normalizer            3.3.2
colorama                      0.4.6
docutils                      0.21.2
grpcio                        1.66.1
grpcio-tools                  1.66.1
idna                          3.10
imagesize                     1.4.1
iniconfig                     2.0.0
MarkupSafe                    2.1.5
mccabe                        0.7.0
mypy-extensions               1.0.0
numpy                         1.26.4
packaging                     24.1
pandas                        2.1.4
pathspec                      0.12.1
pip                           24.0
platformdirs                  4.3.6
pluggy                        1.5.0
poetry-core                   1.9.0
protobuf                      5.28.2
pyarrow                       17.0.0
pycodestyle                   2.12.1
pyflakes                      3.2.0
Pygments                      2.18.0
pytest                        8.3.3
python-dateutil               2.9.0.post0
pytz                          2024.2
setuptools                    75.1.0
six                           1.16.0
snowballstemmer               2.2.0
sphinxcontrib-applehelp       2.0.0
sphinxcontrib-devhelp         2.0.0
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 2.0.0
tzdata                        2024.2
urllib3                       2.2.3
winkerberos                   0.12.0`

+ Finally, I tried installing the PythonSDK package using this command: `pip install --no-index --no-deps volue.mesh-1.9.0.zip` which unfortunately threw me the error that: 

`Processing c:\users\XXX\pythoninstallation\wheels\volue.mesh-1.9.0.zip
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      ERROR: Could not find a version that satisfies the requirement poetry-core>=1.9.0 (from versions: none)
      ERROR: No matching distribution found for poetry-core>=1.9.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

Have I forgotten anything? Any help is very much appreciated!

Best,
Kathinka

**Comment by tnoczyns-volue** [comment]
I'll look into this beginning next week.

**Comment by AKRittinghausen** [comment]
I have good news, we managed with a little workaround. It was very specific for our problem, but just for clarity I will share:

We placed the .zip file in a folder that contained the following wheel files:
![image](https://github.com/user-attachments/assets/774ad644-eadb-44b2-bc64-08f93d213e55)

Then we ran `pip install volue.mesh-1.9.0.zip --no-index -f .`
And that worked...

The total list of packages looks like this: 
`Package         Version
--------------- -----------
bidict          0.23.1
grpcio          1.66.1
numpy           2.1.1
pip             24.0
protobuf        5.27.2
pyarrow         17.0.0
python-dateutil 2.9.0.post0
setuptools      65.5.0
six             1.16.0
volue.mesh      1.9.0
winkerberos     0.12.0`

all is installed for Python 3.11.8

Sorry for the bother, have a great weekend :)
