### ISSUE TITLE
[Optimisation] Please add Example how with use of SDK trigger optimization 

### ISSUE THREAD

**Issue by rudzkipl** [Volue-Public/energy-mesh-python#513]
**Is your feature request related to a problem? Please describe.**
Our customers use more and more Python SDK. In many cases they trigger simulation via SDK. 
In relation to it they would like to use possibility to trigger Optimizations. 

**Describe the solution you'd like**
Please add to the documentation example how it can be done with connection to Optimal Gateway and its API (fe. http://localhost:18261/gateway/#api) based on query to Mesh about detected value change or simulation result (if even possible). 

**Describe alternatives you've considered**
Using PowerShell, but once customers switch to Python, they would like to use same language/spec. 

**Additional context**
![image](https://github.com/user-attachments/assets/2d51096e-6c30-4e91-a1d2-75361fcfc580)

**Comment by erny-powel** [comment]
Mesh and the Mesh Python SDK does not have any knowledge of optimisations or Optimal Gateway. If Optimal Gateway doesn't ship with the necessary documentation you'll have to make a request over in https://github.com/Volue/energy-optimal-gateway/. Unfortunately I can't transfer the issue :(.

**Comment by rudzkipl** [comment]
It is not about the example for Gateway, we know this.
The requests comes from customer using Python SDK (A Energi) running simulations:
https://volue-public.github.io/energy-mesh-python/examples.html#run-simulations

He said the example for optimization is missing, as we Volue recommend use of Python, it should be there ;) 

Example call to Gateway API:
```
{
  "optimizationCase": "CaseName",
  "modelName": "ModelName",
  "startDate": "2024-10-08T22:00:00.000Z",
  "endDate": "2024-10-09T22:00:00.000Z",
  "optimizationId": "00000000-0000-0001-0002-000000000000"
}
```
Optimization Case and Model are/can be fetched from Mesh. 

Let's say Customer would like to run all optimizations under "Creek 1" case in Mesh structure. 
For now he would need to manually add each case name to Python SDK, but with integration with Mesh he could search for all optimization cases with special name, parameter, etc. 

In few cases the caseId (GUID) needs to be used, fe:
`  "caseId": "6b383db5-fb45-41ec-91ed-c8317371a84b",`
and this can be fetched from Mesh as well. 

So the example could be like:
1) Fetch all Optimization cases names with fe. "_SHOP" in name.
2) Check last time optimization was executed (optional),
3) Make a call to Gateway,
4) Check for status of Optimization (optional),
5) Check result from Optimal Log (optional),
6) Save the script verbose results to log file(optional).

**Comment by simia** [comment]
Points 2-6 are not Mesh Python SDK related and point 1 can be achieved using existing example - https://github.com/Volue-Public/energy-mesh-python/blob/master/src/volue/mesh/examples/traverse_model.py
