### ISSUE TITLE
start_time parameter not working as expected for read_timeseries_points

### ISSUE THREAD

**Issue by asmunds** [Volue-Public/energy-mesh-python#517]
Mesh Python SDK version: 1.9.0
Mesh version: 2.15.1+7
Python version: 3.12.1
Operating System (Windows, Ubuntu, etc.): Windows

I am running the following call:
```

            timeseries = session.read_timeseries_points(
                target=target,
                start_time=start_time,
                end_time=end_time
            )
            timeseries = timeseries.arrow_table.to_pandas().set_index('utc_time')['value'].dropna()
            timeseries = timeseries.tz_localize('utc').tz_convert('Europe/Oslo')
```

where 

```
target = 'Model/Agder/Mesh.To_Areas/Norge.To_HydroForecast/HydroForecast.To_InflowWatercourse/Uldal.To_InflowCatchment/Høvringen.Inflow_bestguess'
start_time = Timestamp('2024-10-03 00:00:00+0200', tz='Europe/Oslo')
end_time = Timestamp('2024-10-08 00:00:00+0200', tz='Europe/Oslo')
```

and I receive back the following result:

```
2024-10-02 01:00:00+02:00    0.20
2024-10-03 01:00:00+02:00    0.15
2024-10-04 01:00:00+02:00    0.30
2024-10-05 01:00:00+02:00    0.30
2024-10-06 01:00:00+02:00    0.30
Name: value, dtype: float64
```

As you can see, the first row in the time series is timestamped _before_ start_time. This seems like a bug to me.

**Comment by simia** [comment]
Hi!
This is intended (and not well described) behavior. In cases when user requests a period with start time not matching any time point in the TS Mesh returns additional time point before requested interval. We will describe this behavior in documentation.

**Comment by asmunds** [comment]
Aha, I see. That makes sense. Thanks.
